Remove Phalanx related code in Fishbone project.

diff --git a/meta-celestica/meta-fishbone/recipes-plat/plat-utils/files/fru-util b/meta-celestica/meta-fishbone/recipes-plat/plat-utils/files/fru-util
--- a/meta-celestica/meta-fishbone/recipes-plat/plat-utils/files/fru-util
+++ b/meta-celestica/meta-fishbone/recipes-plat/plat-utils/files/fru-util
@@ -29,7 +29,6 @@ command=(
 "come come_fru"
 "fb fb_fru"
 "switch switch_fru"
-"lb lc_fru"
 )
 
 board_type=$(board_type)
@@ -54,20 +53,6 @@ FBEEPROM_I2C_BUS=39
 FBEEPROM_I2C_ADDR=56
 
 #FAN Module
-if [ "$board_type" = "Phalanx" ]; then
-FAN_EEPROM_MAX=5
-FAN1_EEPROM_I2C_BUS=36
-FAN1_EEPROM_I2C_ADDR=50
-FAN2_EEPROM_I2C_BUS=35
-FAN2_EEPROM_I2C_ADDR=50
-FAN3_EEPROM_I2C_BUS=34
-FAN3_EEPROM_I2C_ADDR=50
-FAN4_EEPROM_I2C_BUS=33
-FAN4_EEPROM_I2C_ADDR=50
-FAN5_EEPROM_I2C_BUS=32
-FAN5_EEPROM_I2C_ADDR=50
-else
-#For Fishbone
 FAN_EEPROM_MAX=4
 FAN1_EEPROM_I2C_BUS=36
 FAN1_EEPROM_I2C_ADDR=50
@@ -77,24 +62,9 @@ FAN3_EEPROM_I2C_BUS=32
 FAN3_EEPROM_I2C_ADDR=50
 FAN4_EEPROM_I2C_BUS=34
 FAN4_EEPROM_I2C_ADDR=50
-fi
 
-#For Phalanx
-if [ "$board_type" = "Phalanx" ]; then
-LC_EEPROM_MAX=2
-LC1_EEPROM_I2C_BUS=9
-LC1_EEPROM_I2C_ADDR=52
-LC2_EEPROM_I2C_BUS=10
-LC2_EEPROM_I2C_ADDR=52
-fi
-
-#For Phalanx PSU
-if [ "$board_type" = "Phalanx" ]; then
-PSU_EEPROM_MAX=4
-else
 #For Fishbone PSU
 PSU_EEPROM_MAX=2
-fi
 
 ############################################
 read_info() {
@@ -102,16 +72,10 @@ read_info() {
 }
 
 psu_present() {
-	if [ "$board_type" = "Phalanx" ]; then
-		if [ $1 -le $PSU_EEPROM_MAX ]; then
-			((val=$(read_info 0 0d psu_${1}_present)))
-		fi
+	if [ $1 -ne 1  ]; then
+		((val=$(read_info 0 0d psu_l_present)))
 	else
-		if [ $1 -ne 1  ]; then
-			((val=$(read_info 0 0d psu_l_present)))
-		else
-			((val=$(read_info 0 0d psu_r_present)))
-		fi
+		((val=$(read_info 0 0d psu_r_present)))
 	fi
 	if [ $val -eq 0 ]; then
 		return 1
@@ -121,16 +85,10 @@ psu_present() {
 }
 
 psu_power() {
-	if [ "$board_type" = "Phalanx" ]; then
-		if [ $1 -le $PSU_EEPROM_MAX ]; then
-			((val=$(read_info 0 0d psu_${1}_status)))
-		fi
+	if [ $1 -ne 1  ]; then
+		((val=$(read_info 0 0d psu_l_status)))
 	else
-		if [ $1 -ne 1  ]; then
-			((val=$(read_info 0 0d psu_l_status)))
-		else
-			((val=$(read_info 0 0d psu_r_status)))
-		fi
+		((val=$(read_info 0 0d psu_r_status)))
 	fi
 	if [ $val -eq 0 ]; then
 		return 1
@@ -140,16 +98,10 @@ psu_power() {
 }
 
 psu_acok() {
-	if [ "$board_type" = "Phalanx" ]; then
-		if [ $1 -le $PSU_EEPROM_MAX ]; then
-			((val=$(read_info 0 0d psu_${1}_ac_status)))
-		fi
+	if [ $1 -ne 1  ]; then
+		((val=$(read_info 0 0d psu_l_ac_status)))
 	else
-		if [ $1 -ne 1  ]; then
-			((val=$(read_info 0 0d psu_l_ac_status)))
-		else
-			((val=$(read_info 0 0d psu_r_ac_status)))
-		fi
+		((val=$(read_info 0 0d psu_r_ac_status)))
 	fi
 	if [ $val -eq 0 ]; then
 		return 1
@@ -164,38 +116,24 @@ psu_eeprom_path()
 }
 
 psu_info() {
-	if [ "$board_type" = "Phalanx" ]; then
-		if [ $1 -le $PSU_EEPROM_MAX ]; then
-			echo "PSU${1} FRU:"
-			$(psu_present $1)
-			if [ $? -eq 0 ]; then
-				echo "Present: Absent"
-				return 1
-			fi
-			echo -e "$(eeprom_data psu$1)"
-		else
-			echo "Invalid PSU number"
+	if [ "$1" == "1" ]; then
+		echo "PSU1 FRU:"
+		$(psu_present 1)
+		if [ $? -eq 0 ]; then
+			echo "Present: Absent"
+			return 1
 		fi
+		echo -e "$(eeprom_data psu1)"
+	elif [ "$1" == "2" ]; then
+		echo "PSU2 FRU:"
+		$(psu_present 2)
+		if [ $? -eq 0 ]; then
+			echo "Present: Absent"
+			return 1
+		fi
+		echo -e "$(eeprom_data psu2)"
 	else
-		if [ "$1" == "1" ]; then
-			echo "PSU1 FRU:"
-			$(psu_present 1)
-			if [ $? -eq 0 ]; then
-				echo "Present: Absent"
-				return 1
-			fi
-			echo -e "$(eeprom_data psu1)"
-		elif [ "$1" == "2" ]; then
-			echo "PSU2 FRU:"
-			$(psu_present 2)
-			if [ $? -eq 0 ]; then
-				echo "Present: Absent"
-				return 1
-			fi
-			echo -e "$(eeprom_data psu2)"
-		else
-			echo "Invalid PSU number"
-		fi
+		echo "Invalid PSU number"
 	fi
 }
 
@@ -204,8 +142,6 @@ psu_usage() {
 	echo "-a    show all psu FRU"
 	if [ "$board_type" = "Fishbone" ]; then
 		echo "-p <1/2>    show specific psu FRU"
-	elif [ "$board_type" = "Phalanx" ]; then
-		echo "-p <1/2/3/4>    show specific psu FRU"
 	else
 		echo "-p <1/2>    show specific psu FRU"
 	fi
@@ -282,28 +218,6 @@ fan_fru() {
 		return 1
 	fi
 	fruid-util fan${i}
-}
-
-lc_fru() {
-	if [ "$board_type" != "Phalanx" ]; then
-		echo "Warning: Board $board_type does not support the function!"
-		exit 0
-	fi
-	if [ $# -lt 1 ] || [ $1 -lt 0 ] || [ $1 -gt ${LC_EEPROM_MAX} ]; then
-		fan_usage
-		return 1
-	fi
-	i=$1
-	echo "LC${i} FRU:"
-	i2c_bus=$((LC${i}_EEPROM_I2C_BUS))
-	i2c_addr=$((LC${i}_EEPROM_I2C_ADDR))
-	if [ -L ${EEPROM_LINK_FILE} ]; then
-		rm -rf ${EEPROM_LINK_FILE}
-	fi
-	ln -s /sys/bus/i2c/devices/i2c-${i2c_bus}/${i2c_bus}-00${i2c_addr}/eeprom  ${EEPROM_LINK_FILE}
-	shift
-	syseeprom $@
-
 }
 
 show_psu_status() {
